Dataset:
  # 사용 데이터셋 : The CASIA dataset is annotated with 10,575 unique people with 494,414 images in total.
  train: Dataset/train
  valid: Dataset/valid
  test: Dataset/valid

  # Test
  test_method: verification
  threshold: 1
  test_weight_path: weights
  save_flag: True
  save_path: result
  show_flag: False
model:
  training: True

  # Re training or Test
  load_name: 250_250_ADAM_PRES18 # training = False,
  load_period: 70

  save_period: 10
  input_size: [250, 250] # height, width
  input_frame_number: 1
  ResNetbase: 18 # resnet base version : 18, 34, 50, 101, 152
  pretrained_base: True #  input_frame_number = 1 일 때만

hyperparameters:

  # model 관련
  image_mean: [0.485, 0.456, 0.406] # R G B
  image_std:  [0.229, 0.224, 0.225] # R G B
  embedding: 128
  margin: 0.2
  semi_hard_negative: True

  # 학습 관련
  epoch: 70
  batch_size: 16
  batch_log: 100
  subdivision: 1
  data_augmentation: False
  num_workers: 8 # the number of multiprocessing workers to use for data preprocessing.
  optimizer: ADAM # ADAM, RMSPROP
  learning_rate: 0.0001
  weight_decay: 0.000001
  decay_lr: 0.9
  decay_step: 1 # 몇 epoch이 지난후 decay_lr을 적용할지
context:
  using_cuda: True
validation:
  valid_size: 8
  eval_period: 10
  tensorboard: True
mlflow:
  using_mlflow: True
  run_name: Face_Recognition




