Dataset:
  train: Dataset/train
  valid: Dataset/valid
  test: Dataset/test
  test_weight_path: weights

  # Test
  save_flag: True
  save_path: result
  show_flag: False
  npy_flag: True
  npy_save_path: npy_result
  video_flag: True
  video_min: None
  video_max: None
  video_fps: 15
  video_name: video
  topk: 7
  except_class_thresh: 0.1
  iou_thresh: 0.1

  # nms 관련
  nms: True
  nms_thresh: 0.5

  plot_class_thresh: 0.1 # 그릴때 score_thresh 보다 큰 것들만 그린다.
  test_graph_path: test_Graph
  test_html_auto_open: False

model:
  training: False
  load_name: 608_608_ADAM_PCENTER_RES18 # training = False,
  save_period: 1
  load_period: 1
  input_size: [608, 608] # height, width
  input_frame_number: 1
  ResNetbase: 18 # resnet base version : 18, 34, 50, 101, 152
  pretrained_base: True #  input_frame_number = 1 일 때만

hyperparameters:

  # model 관련
  image_mean: [0.485, 0.456, 0.406] # R G B
  image_std:  [0.229, 0.224, 0.225] # R G B

  # 학습 관련
  epoch: 10
  batch_size: 8
  batch_log: 100
  subdivision: 1
  data_augmentation: False
  num_workers: 8 # the number of multiprocessing workers to use for data preprocessing.
  optimizer: ADAM # ADAM, RMSPROP
  lambda_off: 1
  lambda_size: 0.1
  learning_rate: 0.0001
  decay_lr: 0.9
  decay_step: 1 # 몇 epoch이 지난후 decay_lr을 적용할지
context:
  using_cuda: True
validation:
  valid_size: 8
  eval_period: 1
  tensorboard: True
  valid_graph_path: valid_Graph
  valid_html_auto_open: False
mlflow:
  using_mlflow: True
  run_name: Animals




