Dataset:
  train: Dataset_WIDER/train
  valid: Dataset_WIDER/valid
  test: Dataset_WIDER/test
  test_weight_path: weights

  # Test
  save_flag: True
  save_path: result
  show_flag: False
  video_flag: True
  video_min: None
  video_max: None
  video_fps: 15
  video_name: video
  topk: 200
  except_class_thresh: 0.5
  iou_thresh: 0.5

  # nms 관련
  nms: False
  nms_thresh: 0.5

  plot_class_thresh: 0.5 # 그릴때 score_thresh 보다 큰 것들만 그린다.
  test_graph_path: test_Graph
  test_html_auto_open: False

model:
  training: False
  load_name: 800_800_ADAM_PCENTER_RES34 # trainㅅing = False,
  save_period: 7
  load_period: 70
  input_size: [800, 800] # height, width
  input_frame_number: 1 # 현재 face Dataset 에서는 무조건 1이어야 함
  ResNetbase: 34 # resnet base version : 18, 34, 50, 101, 152
  pretrained_base: True #  input_frame_number = 1 일 때만

hyperparameters:

  # model 관련
  image_mean: [0.485, 0.456, 0.406] # R G B
  image_std:  [0.229, 0.224, 0.225] # R G B

  # 학습 관련
  epoch: 70
  batch_size: 8
  batch_log: 100
  subdivision: 1
  data_augmentation: True
  num_workers: 8 # the number of multiprocessing workers to use for data preprocessing.
  optimizer: ADAM # ADAM, RMSPROP
  lambda_off: 1
  lambda_size: 0.1
  lambda_landmark: 0.1
  learning_rate: 0.001
  weight_decay: 0.000001
  decay_lr: 0.9
  decay_step: 10 # 몇 epoch이 지난후 decay_lr을 적용할지
context:
  using_cuda: True

validation:
  valid_size: 8
  eval_period: 7
  tensorboard: True
  valid_graph_path: valid_Graph
  valid_html_auto_open: False
mlflow:
  using_mlflow: True
  run_name: CenterFace


