Dataset:
  train: valid
  valid: valid
  test: valid
  test_weight_path: weights

  # Test
  save_flag: True
  save_path: result
  npy_flag: True
  npy_save_path: npy_result
  show_flag: False
  video_flag: False
  video_min: None
  video_max: None
  video_fps: 15
  video_name: temp
  multiperclass: False
  nms_thresh: 0.1
  nms_topk: 200 # 전체 다하면(-1) 너무 오래걸림.
  iou_thresh: 0.1
  except_class_thresh: 0.01 #0.05
  plot_class_thresh: 0.01 # 그릴때 score_thresh 보다 큰 것들만 그린다.
  test_graph_path: test_Graph
  test_html_auto_open: False


model:
  training: True
  load_name: 608_608_ADAM_PRes_18_1frame # training = False,
  save_period: 1
  load_period: 3
  input_size: [608, 608] # height, width
  input_frame_number: 1
  base: 18 # only 18, 34
  pretrained_base: True

hyperparameters:

  # model 관련
  image_mean: [0.485, 0.456, 0.406] # R G B
  image_std:  [0.229, 0.224, 0.225] # R G B
  offset_alloc_size: [64, 64] # height, width / 1 -> 2 -> 3 진행 될때 마다 2배씩 증가 / 입력사이즈 최대크기 2048 X 2048(h,w)에 대비
  anchors: '{"shallow": [(10, 13), (16, 30), (33, 23)],
            "middle": [(30, 61), (62, 45), (59, 119)],
            "deep": [(116, 90), (156, 198), (373, 326)]}'

  # 학습 관련
  epoch: 30
  batch_log: 100
  batch_size: 4
  batch_interval: 10 # multiscale을 몇 배치마다 할껀지?
  subdivision: 1
  multiscale: True
  factor_scale: [10, 9] # (10 ~ 19)*32 / 직사각형 데이터 학습시 dataloader.py 에가서 multiscale전략을 바꿔야한다.
  ignore_threshold: 0.7
  dynamic: True
  data_augmentation: False
  num_workers: 8 # the number of multiprocessing workers to use for data preprocessing.
  optimizer: ADAM # ADAM, RMSPROP, SGD
  learning_rate: 0.001
  decay_lr: 0.9
  decay_step: 1 # 몇 epoch이 지난후 decay_lr을 적용할지
context:
  using_cuda: True
validation:
  valid_size: 4
  eval_period: 1
  tensorboard: True
  valid_graph_path: valid_Graph
  valid_html_auto_open: False
mlflow:
  using_mlflow: True
  run_name: MountainDetection





